# Generated by Django 5.1.6 on 2025-02-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_tools', '0002_syncsession_syncerror'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='syncerror',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='syncsession',
            options={'get_latest_by': 'start_time', 'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='syncsession',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syncerror',
            name='object_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='syncsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncsession',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20),
        ),
    ]
